### ISSUE TITLE
DB structure question.

### ISSUE THREAD

**Issue by Nick-OC97** [afrith/census-graphql-api#26]
Hi @afrith, this project is amazing thank you so much you should put a link somewhere so people can buy you a coffee or something! I was just wondering how you structure your DB so that it is able to calculate which sub place a given set of co ordinates is in so quickly? Or is there another reason its so fast?

**Comment by afrith** [comment]
Hi Nick! The database uses [PostGIS](https://postgis.net/), and all credit for its speed must go to the clever people who designed the spatial indexing in PostGIS which makes those queries so fast.
